// /server/src/modules/auth/services/auth.service.js

const bcrypt = require("bcrypt");

const {
  createSession,
  getSession,
  deleteSession,
} = require("../repositories/session.repository");

const { createUser, findByEmail } = require("../repositories/user.repository");

const SALT_ROUNDS = 10;

/**
 * =========================================================
 * AUTH SERVICE
 * =========================================================
 *
 * PURPOSE:
 * Core business logic for authentication.
 *
 * RESPONSIBILITIES:
 * - User registration (hashing + persistence)
 * - Credential validation (login)
 * - Session lifecycle management
 *
 * IMPORTANT DESIGN DECISIONS:
 * - Session creation is centralized in ONE place
 *   -> createLoginSession()
 *
 * - loginWithPassword() ONLY validates credentials
 *   -> does NOT create sessions
 *
 * This prevents:
 * - Duplicate sessions
 * - Hidden side effects
 * - Debugging confusion
 *
 * =========================================================
 */

/**
 * =========================================================
 * REGISTER USER
 * =========================================================
 *
 * FLOW:
 * 1. Check if user already exists
 * 2. Hash password securely
 * 3. Persist user to database
 *
 * RETURNS:
 * - Newly created user row from database
 */
const registerUser = async ({ email, password }) => {
  const existing = await findByEmail(email);

  // TODO: Implement email verification to enable silent login on duplicate registration.
  // See Story: Implement Email Verification on Register
  if (existing) {
    const err = new Error("An account with that email already exists");
    err.status = 409;
    err.code = "DUPLICATE_ERROR";
    throw err;
  }

  const passwordHash = await bcrypt.hash(password, SALT_ROUNDS);

  const user = await createUser({ email, passwordHash });

  return user;
};

/**
 * =========================================================
 * LOGIN (CREDENTIAL VALIDATION ONLY)
 * =========================================================
 *
 * PURPOSE:
 * Validate email + password WITHOUT side effects
 *
 * IMPORTANT:
 * - Does not create session
 * - ONLY verifies credentials
 * - Returns snake_case fields mapped to camelCase for consistency
 *
 * RETURNS:
 * - { userId, email } if valid
 * - null if invalid
 */
const loginWithPassword = async ({ email, password }) => {
  const user = await findByEmail(email);

  if (!user) return null;

  const isMatch = await bcrypt.compare(password, user.password_hash);

  if (!isMatch) return null;

  return {
    userId: user.user_id,
    email: user.email,
  };
};

/**
 * =========================================================
 * CREATE LOGIN SESSION (SINGLE SOURCE OF TRUTH)
 * =========================================================
 *
 * PURPOSE:
 * Create a new session AFTER credentials are validated.
 *
 * FLOW:
 * 1. Calculate session expiry (SESSION_TTL from env)
 * 2. Persist session to database
 * 3. Return sessionId for cookie usage
 *
 * NOTE:
 * - sessionId is generated by Postgres (gen_random_uuid())
 * - expiresAt is calculated here as it is business logic
 *
 * RETURNS:
 * - { sessionId }
 */
const createLoginSession = async (userId) => {
  if (!userId) {
    throw new Error("userId is required to create a session");
  }

  const expiresAt = new Date(Date.now() + (parseInt(process.env.SESSION_TTL, 10) || 1000 * 60 * 30));

  const session = await createSession(userId, expiresAt);

  return { sessionId: session.session_id };
};

/**
 * =========================================================
 * VALIDATE SESSION
 * =========================================================
 *
 * PURPOSE:
 * Check if session exists and has not expired.
 * Expiry is enforced at the database query level.
 *
 * RETURNS:
 * - { sessionId, userId } if valid
 * - null if invalid or expired
 */
const validateSession = async (sessionId) => {
  if (!sessionId) return null;

  const session = await getSession(sessionId);
  if (!session) return null;

  return {
    sessionId,
    userId: session.user_id,
  };
};

/**
 * =========================================================
 * LOGOUT (SESSION INVALIDATION)
 * =========================================================
 *
 * PURPOSE:
 * Destroy session on logout.
 *
 * SAFE:
 * - No-op if sessionId missing
 */
const logout = async (sessionId) => {
  if (!sessionId) return;

  await deleteSession(sessionId);
};

module.exports = {
  registerUser,
  loginWithPassword,
  createLoginSession,
  validateSession,
  logout,
};