// /server/tests/api/trades.test.js

const request = require("supertest");
const app = require("../../src/app");
const {
  validTrade,
  invalidTrade,
  openTrade,
  createOpenTrade,
} = require("../fixtures/trades");
const { getAuthCookie, clearDatabase } = require("../fixtures/auth");

/**
 * =========================================================
 * TRADE API TEST SUITE
 * =========================================================
 *
 * PURPOSE:
 * Validates all trade-related business logic including
 * validation rules, data normalization, and API responses.
 *
 * COVERAGE:
 * - Trade creation success path
 * - Validation failures (required fields, numeric rules, enums)
 * - Data normalization and response structure
 * - API contract enforcement for trade-related endpoints
 *
 * WHY THIS EXISTS:
 * This file focuses strictly on TRADE DOMAIN LOGIC.
 *
 * It does NOT test:
 * - Middleware behavior (requestId, logging)
 * - Infrastructure concerns
 *
 * Those are covered in:
 * → app.test.js
 *
 * DESIGN PRINCIPLES:
 * - Tests validate behavior, not implementation details
 * - Assertions are flexible where appropriate (regex vs exact match)
 * - Each test maps to a real-world failure or use case
 * =========================================================
 */

describe("Trade API", () => {
  let cookie;

  afterAll(async () => {
    await clearDatabase();
  });

  /**
   * Full isolation between tests.
   * Clears the test database and creates a fresh
   * authenticated session before each test.
   */
  beforeEach(async () => {
    await clearDatabase();
    cookie = await getAuthCookie();
  });

  // =========================
  // Test Case 1.1
  // Successful Trade Creation
  // =========================
  /**
   * Validates that a properly structured trade
   * is successfully created and returned.
   *
   * EXPECTED:
   * - HTTP 201 status
   * - Response contains created trade with correct symbol
   *
   * WHY:
   * - Confirms full request lifecycle works
   * - Ensures integration between controller → service → repository
   */
  it("creates a trade", async () => {
    const res = await request(app)
      .post("/api/trades")
      .set("Cookie", cookie)
      .send(validTrade());

    expect(res.status).toBe(201);
    expect(res.body.data.symbol).toBe("AAPL");
  });

  // =========================
  // Test Case 1.2
  // Missing Required Fields
  // =========================
  /**
   * Validates that missing required fields
   * result in a proper validation error.
   *
   * EXPECTED:
   * - HTTP 400 status
   * - Standardized error response
   * - Message indicates missing required data
   *
   * WHY:
   * - Prevents incomplete data from entering the system
   * - Enforces contract between client and API
   */
  it("rejects missing required fields", async () => {
    const res = await request(app)
      .post("/api/trades")
      .set("Cookie", cookie)
      .send(invalidTrade());

    expect(res.status).toBe(400);
    expect(res.body.error).toBeDefined();
    expect(res.body.error.message).toMatch(/required/i);
  });

  // =========================
  // Test Case 1.3
  // Invalid Numeric Values
  // =========================
  /**
   * Validates that numeric constraints are enforced.
   *
   * EXAMPLES:
   * - Negative entryPrice
   * - Invalid quantity
   *
   * EXPECTED:
   * - HTTP 400 status
   * - Message indicates numeric validation failure
   *
   * WHY:
   * - Prevents invalid financial calculations
   * - Ensures data integrity for P&L logic
   */
  it("rejects invalid numeric values", async () => {
    const res = await request(app)
      .post("/api/trades")
      .set("Cookie", cookie)
      .send({
        symbol: "AAPL",
        type: "BUY",
        entryPrice: -100,
        quantity: 1,
      });

    expect(res.status).toBe(400);
    expect(res.body.error.message).toMatch(/greater than 0|invalid numeric/i);
  });

  // =========================
  // Test Case 1.4
  // Partial Exit Data
  // =========================
  /**
   * Validates that exitPrice and exitTime
   * must be provided together.
   *
   * INVALID CASE:
   * - exitPrice present without exitTime
   *
   * EXPECTED:
   * - HTTP 400 status
   * - Message indicates incomplete exit data
   *
   * WHY:
   * - Prevents inconsistent trade states
   * - Ensures accurate trade lifecycle tracking
   */
  it("rejects partial exit data", async () => {
    const res = await request(app)
      .post("/api/trades")
      .set("Cookie", cookie)
      .send({
        symbol: "AAPL",
        type: "BUY",
        entryPrice: 100,
        quantity: 1,
        exitPrice: 110,
      });

    expect(res.status).toBe(400);
    expect(res.body.error.message).toMatch(/exit.*both|incomplete/i);
  });

  // =========================
  // Test Case 1.5
  // Response Normalization
  // =========================
  /**
   * Validates that the API returns a fully normalized trade object.
   *
   * EXPECTED:
   * - trade_id is generated by Postgres
   * - created_at timestamp exists
   * - entry_price is returned as a string (Postgres NUMERIC type)
   *
   * WHY:
   * - Ensures backend is responsible for data shaping
   * - Prevents frontend reliance on raw/unprocessed data
   */
  it("returns clean trade response structure after creation", async () => {
    const res = await request(app)
      .post("/api/trades")
      .set("Cookie", cookie)
      .send({
        symbol: "AAPL",
        type: "BUY",
        entryPrice: 100,
        quantity: 1,
      });

    expect(res.status).toBe(201);
    expect(res.body.data.trade_id).toBeDefined();
    expect(res.body.data.created_at).toBeDefined();
    expect(typeof res.body.data.entry_price).toBe("string");
  });

  // =========================
  // Test Case 1.6
  // Invalid Trade Type
  // =========================
  /**
   * Validates that only supported trade types are accepted.
   *
   * INVALID TYPES:
   * - LONG
   * - SHORT
   * - arbitrary strings
   *
   * EXPECTED:
   * - HTTP 400 status
   * - Message indicates invalid trade type
   *
   * WHY:
   * - Enforces strict enum constraints
   * - Prevents undefined behavior in business logic
   */
  it("rejects invalid trade types", async () => {
    const invalidTypes = ["LONG", "SHORT", "INVALID"];

    for (const type of invalidTypes) {
      const res = await request(app)
        .post("/api/trades")
        .set("Cookie", cookie)
        .send({
          symbol: "AAPL",
          type,
          entryPrice: 100,
          quantity: 1,
        });

      expect(res.status).toBe(400);
      expect(res.body.error.message).toMatch(/invalid trade type/i);
    }
  });

  // =========================
  // Test Case 1.7
  // Negative Exit Price
  // =========================
  /**
   * Validates that a negative exit price is rejected.
   *
   * WHY:
   * - Prevents invalid financial data
   * - Enforces positive number constraint on exit price
   */
  it("rejects negative exit price", async () => {
    const res = await request(app)
      .post("/api/trades")
      .set("Cookie", cookie)
      .send({
        symbol: "AAPL",
        type: "BUY",
        entryPrice: 100,
        exitPrice: -50,
        quantity: 1,
      });

    expect(res.status).toBe(400);
    expect(res.body.error).toBeDefined();
    expect(res.body.error.message).toMatch(/greater than 0/i);
    expect(res.body.error.code).toBe("VALIDATION_ERROR");
  });

  // =========================
  // Test Case 1.8
  // Zero Quantity
  // =========================
  /**
   * Validates that a zero quantity is rejected.
   *
   * WHY:
   * - A trade with zero quantity is meaningless
   * - Enforces positive integer constraint on quantity
   */
  it("rejects zero quantity", async () => {
    const res = await request(app)
      .post("/api/trades")
      .set("Cookie", cookie)
      .send({
        symbol: "AAPL",
        type: "BUY",
        entryPrice: 100,
        quantity: 0,
      });

    expect(res.status).toBe(400);
    expect(res.body.error).toBeDefined();
    expect(res.body.error.message).toMatch(/greater than 0/i);
    expect(res.body.error.code).toBe("VALIDATION_ERROR");
  });

  // =========================
  // Test Case 1.9
  // Exit Time Before Entry Time
  // =========================
  /**
   * Validates that exit time cannot be before entry time.
   *
   * WHY:
   * - A trade cannot close before it opens
   * - Enforces temporal integrity of trade lifecycle
   */
  it("rejects exit time before entry time", async () => {
    const res = await request(app)
      .post("/api/trades")
      .set("Cookie", cookie)
      .send({
        symbol: "AAPL",
        type: "BUY",
        entryPrice: 100,
        exitPrice: 110,
        quantity: 1,
        entryTime: "2024-01-10T10:00:00",
        exitTime: "2024-01-09T10:00:00",
      });

    expect(res.status).toBe(400);
    expect(res.body.error).toBeDefined();
    expect(res.body.error.message).toMatch(/exit time/i);
    expect(res.body.error.code).toBe("VALIDATION_ERROR");
  });

  // =========================
  // Test Case 1.10
  // Close an open trade
  // =========================
  /**
   * Validates that a PATCH to /close updates the trade
   * to closed status with exit data populated.
   *
   * EXPECTED:
   * - HTTP 200
   * - trade_status is "closed"
   * - exit_price and closed_at are set
   */
  it("closes an open trade", async () => {
    const trade = await createOpenTrade(cookie);

    const res = await request(app)
      .patch(`/api/trades/${trade.trade_id}/close`)
      .set("Cookie", cookie)
      .send({
        exitPrice: 150,
        exitTime: "2024-01-10T11:00:00",
      });

    expect(res.status).toBe(200);
    expect(res.body.data.trade_status).toBe("closed");
    expect(res.body.data.exit_price).toBeDefined();
    expect(res.body.data.closed_at).toBeDefined();
  });

  // =========================
  // Test Case 1.11
  // Cannot close an already closed trade
  // =========================
  /**
   * Validates that closing an already-closed trade
   * returns a 400 with a descriptive error.
   *
   * EXPECTED:
   * - HTTP 400
   * - error code TRADE_ALREADY_CLOSED
   */
  it("returns 400 when closing an already closed trade", async () => {
    const trade = await createOpenTrade(cookie);

    // Close it once
    await request(app)
      .patch(`/api/trades/${trade.trade_id}/close`)
      .set("Cookie", cookie)
      .send({ exitPrice: 150, exitTime: "2024-01-10T11:00:00" });

    // Close it again
    const res = await request(app)
      .patch(`/api/trades/${trade.trade_id}/close`)
      .set("Cookie", cookie)
      .send({ exitPrice: 155, exitTime: "2024-01-10T12:00:00" });

    expect(res.status).toBe(400);
    expect(res.body.error.code).toBe("TRADE_ALREADY_CLOSED");
  });

  // =========================
  // Test Case 1.12
  // Cannot close another user's trade
  // =========================
  /**
   * Validates that closing a trade belonging to a different
   * user returns 403.
   *
   * EXPECTED:
   * - HTTP 403
   * - error code FORBIDDEN
   */
  it("returns 403 when closing another user's trade", async () => {
    const trade = await createOpenTrade(cookie);

    // Create a second authenticated user
    const otherCookie = await getAuthCookie();

    const res = await request(app)
      .patch(`/api/trades/${trade.trade_id}/close`)
      .set("Cookie", otherCookie)
      .send({ exitPrice: 150, exitTime: "2024-01-10T11:00:00" });

    expect(res.status).toBe(403);
    expect(res.body.error.code).toBe("FORBIDDEN");
  });

  // =========================
  // Test Case 1.13
  // Cannot close a non-existent trade
  // =========================
  /**
   * Validates that closing a trade that does not exist
   * returns 404.
   *
   * EXPECTED:
   * - HTTP 404
   * - error code NOT_FOUND
   */
  it("returns 404 when closing a non-existent trade", async () => {
    const res = await request(app)
      .patch("/api/trades/00000000-0000-0000-0000-000000000000/close")
      .set("Cookie", cookie)
      .send({ exitPrice: 150, exitTime: "2024-01-10T11:00:00" });

    expect(res.status).toBe(404);
    expect(res.body.error.code).toBe("NOT_FOUND");
  });

  // =========================
  // Test Case 1.14
  // Delete a trade
  // =========================
  /**
   * Validates that a trade is successfully deleted.
   *
   * EXPECTED:
   * - HTTP 200
   * - Trade no longer returned in findAll
   */
  it("deletes a trade", async () => {
    const trade = await createOpenTrade(cookie);

    const res = await request(app)
      .delete(`/api/trades/${trade.trade_id}`)
      .set("Cookie", cookie);

    expect(res.status).toBe(200);
    expect(res.body.message).toBe("Trade deleted");

    // Confirm it's gone
    const listRes = await request(app).get("/api/trades").set("Cookie", cookie);

    const ids = listRes.body.data.map((t) => t.trade_id);
    expect(ids).not.toContain(trade.trade_id);
  });

  // =========================
  // Test Case 1.15
  // Cannot delete another user's trade
  // =========================
  /**
   * Validates that deleting a trade belonging to a different
   * user returns 403.
   *
   * EXPECTED:
   * - HTTP 403
   * - error code FORBIDDEN
   */
  it("returns 403 when deleting another user's trade", async () => {
    const trade = await createOpenTrade(cookie);

    const otherCookie = await getAuthCookie();

    const res = await request(app)
      .delete(`/api/trades/${trade.trade_id}`)
      .set("Cookie", otherCookie);

    expect(res.status).toBe(403);
    expect(res.body.error.code).toBe("FORBIDDEN");
  });

  // =========================
  // Test Case 1.16
  // Cannot delete a non-existent trade
  // =========================
  /**
   * Validates that deleting a trade that does not exist
   * returns 404.
   *
   * EXPECTED:
   * - HTTP 404
   * - error code NOT_FOUND
   */
  it("returns 404 when deleting a non-existent trade", async () => {
    const res = await request(app)
      .delete("/api/trades/00000000-0000-0000-0000-000000000000")
      .set("Cookie", cookie);

    expect(res.status).toBe(404);
    expect(res.body.error.code).toBe("NOT_FOUND");
  });

  // =========================
  // Test Case 1.17
  // Edit a trade — success
  // =========================
  /**
   * Validates that a trade is successfully updated
   * with new field values.
   *
   * EXPECTED:
   * - HTTP 200
   * - Returned trade reflects updated values
   */
  it("edits a trade", async () => {
    const trade = await createOpenTrade(cookie);

    const res = await request(app)
      .put(`/api/trades/${trade.trade_id}`)
      .set("Cookie", cookie)
      .send({
        symbol: "TSLA",
        type: "SELL",
        entryPrice: 200,
        quantity: 2,
        entryTime: "2026-04-21T09:00:00Z",
      });

    expect(res.status).toBe(200);
    expect(res.body.data.symbol).toBe("TSLA");
    expect(res.body.data.trade_type).toBe("SELL");
    expect(res.body.data.trade_status).toBe("open");
  });

  // =========================
  // Test Case 1.18
  // Edit recalculates trade_status and closed_at
  // =========================
  /**
   * Validates that adding an exitPrice on edit
   * recalculates trade_status to closed.
   *
   * EXPECTED:
   * - HTTP 200
   * - trade_status is "closed"
   * - closed_at is set
   */
  it("recalculates trade_status when exitPrice is added on edit", async () => {
    const trade = await createOpenTrade(cookie);

    const res = await request(app)
      .put(`/api/trades/${trade.trade_id}`)
      .set("Cookie", cookie)
      .send({
        symbol: "AAPL",
        type: "BUY",
        entryPrice: 100,
        quantity: 1,
        entryTime: "2026-04-21T09:00:00Z",
        exitPrice: 150,
        exitTime: "2026-04-21T10:00:00Z",
      });

    expect(res.status).toBe(200);
    expect(res.body.data.trade_status).toBe("closed");
    expect(res.body.data.closed_at).toBeDefined();
  });

  // =========================
  // Test Case 1.19
  // Cannot edit another user's trade
  // =========================
  /**
   * Validates that editing a trade belonging to a different
   * user returns 403.
   *
   * EXPECTED:
   * - HTTP 403
   * - error code FORBIDDEN
   */
  it("returns 403 when editing another user's trade", async () => {
    const trade = await createOpenTrade(cookie);
    const otherCookie = await getAuthCookie();

    const res = await request(app)
      .put(`/api/trades/${trade.trade_id}`)
      .set("Cookie", otherCookie)
      .send({
        symbol: "AAPL",
        type: "BUY",
        entryPrice: 100,
        quantity: 1,
        entryTime: "2026-04-21T09:00:00Z",
      });

    expect(res.status).toBe(403);
    expect(res.body.error.code).toBe("FORBIDDEN");
  });

  // =========================
  // Test Case 1.20
  // Cannot edit a non-existent trade
  // =========================
  /**
   * Validates that editing a trade that does not exist
   * returns 404.
   *
   * EXPECTED:
   * - HTTP 404
   * - error code NOT_FOUND
   */
  it("returns 404 when editing a non-existent trade", async () => {
    const res = await request(app)
      .put("/api/trades/00000000-0000-0000-0000-000000000000")
      .set("Cookie", cookie)
      .send({
        symbol: "AAPL",
        type: "BUY",
        entryPrice: 100,
        quantity: 1,
        entryTime: "2026-04-21T09:00:00Z",
      });

    expect(res.status).toBe(404);
    expect(res.body.error.code).toBe("NOT_FOUND");
  });

  // =========================
  // Test Case 1.21
  // Edit validation applies
  // =========================
  /**
   * Validates that existing validation rules
   * are enforced on edit payloads.
   *
   * EXPECTED:
   * - HTTP 400
   * - error code VALIDATION_ERROR
   */
  it("returns 400 when edit payload fails validation", async () => {
    const trade = await createOpenTrade(cookie);

    const res = await request(app)
      .put(`/api/trades/${trade.trade_id}`)
      .set("Cookie", cookie)
      .send({
        symbol: "AAPL",
        type: "BUY",
        entryPrice: -100,
        quantity: 1,
        entryTime: "2026-04-21T09:00:00Z",
      });

    expect(res.status).toBe(400);
    expect(res.body.error.code).toBe("VALIDATION_ERROR");
  });
});
