// /server/tests/api/trades.test.js

const request = require("supertest");
const app = require("../../src/app");
const { validTrade, invalidTrade } = require("../fixtures/trades");
const { getAuthCookie, clearDatabase } = require("../fixtures/auth");

/**
 * =========================================================
 * TRADE API TEST SUITE
 * =========================================================
 *
 * PURPOSE:
 * Validates all trade-related business logic including
 * validation rules, data normalization, and API responses.
 *
 * COVERAGE:
 * - Trade creation success path
 * - Validation failures (required fields, numeric rules, enums)
 * - Data normalization and response structure
 * - API contract enforcement for trade-related endpoints
 *
 * WHY THIS EXISTS:
 * This file focuses strictly on TRADE DOMAIN LOGIC.
 *
 * It does NOT test:
 * - Middleware behavior (requestId, logging)
 * - Infrastructure concerns
 *
 * Those are covered in:
 * → app.test.js
 *
 * DESIGN PRINCIPLES:
 * - Tests validate behavior, not implementation details
 * - Assertions are flexible where appropriate (regex vs exact match)
 * - Each test maps to a real-world failure or use case
 * =========================================================
 */

describe("Trade API", () => {
  let cookie;

  afterAll(async () => {
    await clearDatabase();
  });

  /**
   * Full isolation between tests.
   * Clears the test database and creates a fresh
   * authenticated session before each test.
   */
  beforeEach(async () => {
    await clearDatabase();
    cookie = await getAuthCookie();
  });

  // =========================
  // Test Case 1.1
  // Successful Trade Creation
  // =========================
  /**
   * Validates that a properly structured trade
   * is successfully created and returned.
   *
   * EXPECTED:
   * - HTTP 201 status
   * - Response contains created trade with correct symbol
   *
   * WHY:
   * - Confirms full request lifecycle works
   * - Ensures integration between controller → service → repository
   */
  it("creates a trade", async () => {
    const res = await request(app)
      .post("/api/trades")
      .set("Cookie", cookie)
      .send(validTrade());

    expect(res.status).toBe(201);
    expect(res.body.data.symbol).toBe("AAPL");
  });

  // =========================
  // Test Case 1.2
  // Missing Required Fields
  // =========================
  /**
   * Validates that missing required fields
   * result in a proper validation error.
   *
   * EXPECTED:
   * - HTTP 400 status
   * - Standardized error response
   * - Message indicates missing required data
   *
   * WHY:
   * - Prevents incomplete data from entering the system
   * - Enforces contract between client and API
   */
  it("rejects missing required fields", async () => {
    const res = await request(app)
      .post("/api/trades")
      .set("Cookie", cookie)
      .send(invalidTrade());

    expect(res.status).toBe(400);
    expect(res.body.error).toBeDefined();
    expect(res.body.error.message).toMatch(/required/i);
  });

  // =========================
  // Test Case 1.3
  // Invalid Numeric Values
  // =========================
  /**
   * Validates that numeric constraints are enforced.
   *
   * EXAMPLES:
   * - Negative entryPrice
   * - Invalid quantity
   *
   * EXPECTED:
   * - HTTP 400 status
   * - Message indicates numeric validation failure
   *
   * WHY:
   * - Prevents invalid financial calculations
   * - Ensures data integrity for P&L logic
   */
  it("rejects invalid numeric values", async () => {
    const res = await request(app)
      .post("/api/trades")
      .set("Cookie", cookie)
      .send({
        symbol: "AAPL",
        type: "BUY",
        entryPrice: -100,
        quantity: 1,
      });

    expect(res.status).toBe(400);
    expect(res.body.error.message).toMatch(/greater than 0|invalid numeric/i);
  });

  // =========================
  // Test Case 1.4
  // Partial Exit Data
  // =========================
  /**
   * Validates that exitPrice and exitTime
   * must be provided together.
   *
   * INVALID CASE:
   * - exitPrice present without exitTime
   *
   * EXPECTED:
   * - HTTP 400 status
   * - Message indicates incomplete exit data
   *
   * WHY:
   * - Prevents inconsistent trade states
   * - Ensures accurate trade lifecycle tracking
   */
  it("rejects partial exit data", async () => {
    const res = await request(app)
      .post("/api/trades")
      .set("Cookie", cookie)
      .send({
        symbol: "AAPL",
        type: "BUY",
        entryPrice: 100,
        quantity: 1,
        exitPrice: 110,
      });

    expect(res.status).toBe(400);
    expect(res.body.error.message).toMatch(/exit.*both|incomplete/i);
  });

  // =========================
  // Test Case 1.5
  // Response Normalization
  // =========================
  /**
   * Validates that the API returns a fully normalized trade object.
   *
   * EXPECTED:
   * - trade_id is generated by Postgres
   * - created_at timestamp exists
   * - entry_price is returned as a string (Postgres NUMERIC type)
   *
   * WHY:
   * - Ensures backend is responsible for data shaping
   * - Prevents frontend reliance on raw/unprocessed data
   */
  it("returns clean trade response structure after creation", async () => {
    const res = await request(app)
      .post("/api/trades")
      .set("Cookie", cookie)
      .send({
        symbol: "AAPL",
        type: "BUY",
        entryPrice: 100,
        quantity: 1,
      });

    expect(res.status).toBe(201);
    expect(res.body.data.trade_id).toBeDefined();
    expect(res.body.data.created_at).toBeDefined();
    expect(typeof res.body.data.entry_price).toBe("string");
  });

  // =========================
  // Test Case 1.6
  // Invalid Trade Type
  // =========================
  /**
   * Validates that only supported trade types are accepted.
   *
   * INVALID TYPES:
   * - LONG
   * - SHORT
   * - arbitrary strings
   *
   * EXPECTED:
   * - HTTP 400 status
   * - Message indicates invalid trade type
   *
   * WHY:
   * - Enforces strict enum constraints
   * - Prevents undefined behavior in business logic
   */
  it("rejects invalid trade types", async () => {
    const invalidTypes = ["LONG", "SHORT", "INVALID"];

    for (const type of invalidTypes) {
      const res = await request(app)
        .post("/api/trades")
        .set("Cookie", cookie)
        .send({
          symbol: "AAPL",
          type,
          entryPrice: 100,
          quantity: 1,
        });

      expect(res.status).toBe(400);
      expect(res.body.error.message).toMatch(/invalid trade type/i);
    }
  });

  // =========================
  // Test Case 1.7
  // Negative Exit Price
  // =========================
  /**
   * Validates that a negative exit price is rejected.
   *
   * WHY:
   * - Prevents invalid financial data
   * - Enforces positive number constraint on exit price
   */
  it("rejects negative exit price", async () => {
    const res = await request(app)
      .post("/api/trades")
      .set("Cookie", cookie)
      .send({
        symbol: "AAPL",
        type: "BUY",
        entryPrice: 100,
        exitPrice: -50,
        quantity: 1,
      });

    expect(res.status).toBe(400);
    expect(res.body.error).toBeDefined();
    expect(res.body.error.message).toMatch(/greater than 0/i);
    expect(res.body.error.code).toBe("VALIDATION_ERROR");
  });

  // =========================
  // Test Case 1.8
  // Zero Quantity
  // =========================
  /**
   * Validates that a zero quantity is rejected.
   *
   * WHY:
   * - A trade with zero quantity is meaningless
   * - Enforces positive integer constraint on quantity
   */
  it("rejects zero quantity", async () => {
    const res = await request(app)
      .post("/api/trades")
      .set("Cookie", cookie)
      .send({
        symbol: "AAPL",
        type: "BUY",
        entryPrice: 100,
        quantity: 0,
      });

    expect(res.status).toBe(400);
    expect(res.body.error).toBeDefined();
    expect(res.body.error.message).toMatch(/greater than 0/i);
    expect(res.body.error.code).toBe("VALIDATION_ERROR");
  });

  // =========================
  // Test Case 1.9
  // Exit Time Before Entry Time
  // =========================
  /**
   * Validates that exit time cannot be before entry time.
   *
   * WHY:
   * - A trade cannot close before it opens
   * - Enforces temporal integrity of trade lifecycle
   */
  it("rejects exit time before entry time", async () => {
    const res = await request(app)
      .post("/api/trades")
      .set("Cookie", cookie)
      .send({
        symbol: "AAPL",
        type: "BUY",
        entryPrice: 100,
        exitPrice: 110,
        quantity: 1,
        entryTime: "2024-01-10T10:00:00",
        exitTime: "2024-01-09T10:00:00",
      });

    expect(res.status).toBe(400);
    expect(res.body.error).toBeDefined();
    expect(res.body.error.message).toMatch(/exit time/i);
    expect(res.body.error.code).toBe("VALIDATION_ERROR");
  });
});
